[package]
name = "Sandbox"
version = "0.1"
lean_version = "nightly-2018-08-23"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "2e636352061a7fefde8db2c2f775ad0e63554ff2"}
